### ISSUE TITLE
Cannot open load file

### ISSUE THREAD

**Issue by nivaca** [alphapapa/magit.sh#1]
I'm getting this error as soon as I run the script:

`command-line-1: Cannot open load file: No such file or directory, magit`

**Comment by alphapapa** [comment]
Did you see this note in the readme?

> Note that this does not install any packages. Magit and its dependencies must already be installed in ~/.emacs.d.

**Comment by nivaca** [comment]
Of course I read it and I have it installed. I use magit al the time.
